# Generated by Django 5.2.13 on 2026-04-27 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_harpr_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='category_health_label',
            field=models.CharField(default='Health', max_length=40),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='category_personal_label',
            field=models.CharField(default='Personal', max_length=40),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='category_study_label',
            field=models.CharField(default='Study', max_length=40),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='category_work_label',
            field=models.CharField(default='Work', max_length=40),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='pomodoro_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='pomodoro_sound_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_public_holidays',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('completed', 'Completed'), ('reopened', 'Re-opened'), ('deleted', 'Moved to trash'), ('restored', 'Restored from trash'), ('purged', 'Permanently deleted')], max_length=20)),
                ('task_title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_log', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
