# Generated by Django 6.1.1 on 2026-09-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_v13_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='pomodoro_notification_enabled',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='pomodoro_sound_enabled',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
